Oratory_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib. staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('video/', include('video.urls')),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('aboutus/',include('aboutus.urls')),
    path('homework/',include('homework.urls')),
    path('vocab/',include('vocab.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('gallery/',include('gallery.urls')),
    path('summernote/',include('django_summernote.urls')),
]


urlpatterns+= staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib. staticfiles.urls import staticfiles_urlpatterns


app_name='articles'
urlpatterns =[
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/',views.article_details, name="detail"),
    
    
]

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns=[
    path('',views.home, name='home'),
]

articles/models.py
 
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from tinymce.models import HTMLField
from froala_editor.fields import FroalaField

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body=HTMLField()
    date = models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(default="default.png", blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE, default=None, null=True, blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
            a= self.body[0:10]+ "..."
            return a
            
        
         

articles/forms.py
from django import forms
from froala_editor.widgets import FroalaEditor
from . import models

class CreateArticle(forms.ModelForm):
    
    body=forms.CharField(widget=FroalaEditor)
    class Meta:
        model=models.Article
        fields={"title", "body", "slug", "thumb"}
        

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from . import forms
# Create your views here.
def  article_list(request):
    articles=Article.objects.all().order_by('date')
    return render(request,"articles/articles_list.html",{'articles': articles})
    
def article_details(request,slug):
    article=Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})
    return HttpResponse(slug)

@login_required(login_url='/accounts/login')
def article_create(request):
    if(request.method=="POST"):
        form =forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect("articles:list")
    else:
        form = forms.CreateArticle
    return render(request, 'articles/article_create.html', {'form':form})

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2 style="font-family: Roboto, sans-serif; text-align: center; font-size: 30px;">Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2 style="font-family: sans-serif;">{{ article.title }}</h2>
        <h3 style="font-family: Roboto, sans-serif;">Written by {{ article.author.username }}</h3>
        <p style="font-family: Roboto, sans-serif;">{{ article.body }}</p>
        <p style="font-family: Roboto, sans-serif;">{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/articles_list.html
<head>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <style>
        body{
            font-family: 'Roboto', sans-serif;
        }
    </style>
</head>
{% extends 'base_layout.html' %}

{% block content%}
    <h1 style="font-family: 'Roboto Mono', monospace; font-size: 48px;">Articles List</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a style="font-family: sans-serif; font-weight: 700; color: black;" href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p style="font-family: Roboto, sans-serif;">{{ article.snippet }}</p>
            <p style="font-family: Roboto, sans-serif;">{{ article.date }}</p>
            <p class="author" style="font-family: Roboto, sans-serif;">added by {{ article.author.username }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}