Oratory_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib. staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('video/', include('video.urls')),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('aboutus/',include('aboutus.urls')),
    path('homework/',include('homework.urls')),
    path('vocab/',include('vocab.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('gallery/',include('gallery.urls')),
    path('summernote/',include('django_summernote.urls')),
]


urlpatterns+= staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aboutus/urls.py
from django.urls import path
from . import views

app_name='aboutus'

urlpatterns=[
    path('',views.aboutus, name='aboutus'),
]

gallery/urls.py
from django.urls import path
from . import views

app_name='gallery'

urlpatterns=[
    path('',views.gallery_homepage, name='gallery'),
]

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns=[
    path('',views.home, name='home'),
]

homework/urls.py
from django.urls import path
from . import views

app_name = 'homework'

urlpatterns = [
    #path('index/',views.index,name='homeworkIndex'),
    path('',views.assignhomework,name='assignhomework'),
    path('<int:sender_id>/<int:reciever_id>/',views.sendhomework,name='sendhomework'),
    path('shuffle',views.shuffle,name='shuffle'),

]

video/urls.py
from django.urls import path
from . import views

app_name='video'
urlpatterns=[
    path('', views.videopage, name="videopage")
]

vocab/urls.py
from django.urls import path
from . import views

app_name='vocab'
urlpatterns = [
    path('',views.storewords,name='storewords'),
    path('addword/',views.newword,name='addword'),
    path('vocablist/', views.wordslist, name='wordlist'),
]

homework/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

homework/forms.py
from django import forms

'''
send_mail(subject, 
        message,
        from_email, 
        recipient_list,
        fail_silently=False,
        auth_user=None, 
        auth_password=None, 
        connection=None, 
        html_message=None
        )
'''
class Homeworkform(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    authuser = forms.CharField(max_length=50,required=False)
    authpassword = forms.CharField(max_length=50,required=False)

    

homework/views.py
from django.shortcuts import render,redirect
from Oratory_site.settings import EMAIL_HOST_USER,EMAIL_HOST_PASSWORD
from django.http import HttpResponse
from .forms import Homeworkform
import random
from .models import Person
from django.core.mail import send_mail
import time
from django.core.exceptions import PermissionDenied


dict = {}
newlist = []


def index(request):
    return HttpResponse("<h1> now we are starting the app at oratory site yeeeee-----</h1>")

def superuseronly(function):
    def inner(request):
        if not request.user.is_superuser:
            raise PermissionDenied
        else:
            return function(request)
    return inner

@superuseronly
def shuffle(request):
    dict.clear()
    newlist.clear()
    nametoemail = Person.objects.all()
    newlist.append('blank')
    for person in nametoemail:
        newlist.append(person.name)
    length = len(newlist)-1
    
    visited = [False for i in range(length)]
    print(len(visited))
    flag,current = 0,0
    for i in range(length):
        while(not flag):
            current = random.randint(0,length-1)
            if (not(visited[current])) and current!=i:
                visited[current] = True
                dict[i+1] = current+1
                flag = 1
        flag = 0
    return render(request,'homework/assign.html',{'newlist':newlist,'dict':dict,'range':range(1,15)})  

def assignhomework(request):
    return render(request,'homework/assign.html',{'newlist':newlist,'dict':dict,'range':range(1,15)})  
'''
class HomeworkForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    authuser = forms.CharField(max_length=50)
    authpassword = forms.CharField(max_length=50)
'''

def sendhomework(request,sender_id,reciever_id):
    sender = Person.objects.get(pk=sender_id)
    reciever = Person.objects.get(pk=reciever_id)
    
    form = Homeworkform(None)
    if request.method == 'POST':
        form = Homeworkform(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_mail = form.cleaned_data['sender']
            authuser = form.cleaned_data['authuser']
            authpassword = form.cleaned_data['authpassword']
            if authpassword == 'None' and authuser == 'None':
                send_mail(subject, message, from_mail, [reciever.email],False)
            else:
                send_mail(subject, message, from_mail, [reciever.email],False, authuser, authpassword,html_message=None)
            redirect('homework:assignhomework')

    return render(request , 'homework/message.html', {'sender':sender,'reciever':reciever,'form':form})

homework/templates/homework/assign.html
{% load static %}

<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOTSTRAP CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>Homework</title>
</head>
<body>

    <header>
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#"><img style="max-width: 40%;" src="{% static 'logo_light2.png' %}"
                alt="logo" /></a></h1></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'home:home' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'aboutus:aboutus' %}">About Us</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gallery:gallery' %}">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'articles:list' %}">Blogs</a>                 
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'video:videopage' %}">Video Of the day</a>                 
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Content
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="#">JAM</a>
                      <a class="dropdown-item" href="{% url 'homework:assignhomework' %}">Homework</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url  'vocab:storewords' %}">Words</a>
                    </div>
                </li>
                
                
              </ul>
            </div>
          </nav>
    </header>
    <h1>Do your work before deadline and live well</h1>
    <a href="{% url 'homework:shuffle' %}">Update home work list</a>
    <ul>
        {% for k,v in dict.items %}
            <li>
                {% load file %}
                <a href="{% url 'homework:sendhomework' k v %}"> #  </a>  {{ newlist|index:k }} ---> {{ newlist|index:v }}
                <br><hr>
            </li>
        {% endfor %}    
    </ul>
</body>
<!-- JQUERY CDN -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<!-- BOOTSTRAP CDN -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</html>


 

homework/templates/homework/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Send Homework</title>
</head>
<body>
    <h1> Here sender will mail </h1>
    <br>
    {{ sender.name }} will write message here to {{ reciever.name }}
    <hr>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_ul }}
            <input type="submit" value="Submit"/>
        </form>
    </div>
</body>
</html>