Oratory_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib. staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('video/', include('video.urls')),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('aboutus/',include('aboutus.urls')),
    path('homework/',include('homework.urls')),
    path('vocab/',include('vocab.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('gallery/',include('gallery.urls')),
    path('summernote/',include('django_summernote.urls')),
]


urlpatterns+= staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aboutus/urls.py
from django.urls import path
from . import views

app_name='aboutus'

urlpatterns=[
    path('',views.aboutus, name='aboutus'),
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib. staticfiles.urls import staticfiles_urlpatterns


app_name='articles'
urlpatterns =[
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/',views.article_details, name="detail"),
    
    
]

gallery/urls.py
from django.urls import path
from . import views

app_name='gallery'

urlpatterns=[
    path('',views.gallery_homepage, name='gallery'),
]

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns=[
    path('',views.home, name='home'),
]

video/urls.py
from django.urls import path
from . import views

app_name='video'
urlpatterns=[
    path('', views.videopage, name="videopage")
]

vocab/urls.py
from django.urls import path
from . import views

app_name='vocab'
urlpatterns = [
    path('',views.storewords,name='storewords'),
    path('addword/',views.newword,name='addword'),
    path('vocablist/', views.wordslist, name='wordlist'),
]

vocab/models.py
from django.db import models

# Create your models here.
class Word(models.Model):
    new_word = models.CharField(max_length=100)
    meaning = models.TextField()
    example = models.TextField()

    def __str__(self):
        return self.new_word

vocab/forms.py
from django import forms

'''
class Word(models.Model):
    new_word = models.CharField(max_length=100)
    meaning = models.TextField()
    example = models.TextField()

    def __str__(self):
        return self.new_word

class Homeworkform(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    authuser = forms.CharField(max_length=50,required=False)
    authpassword = forms.CharField(max_length=50,required=False)


'''

class Addwordform(forms.Form):
    word = forms.CharField(max_length=100)
    meaning = forms.CharField(widget=forms.Textarea)
    example = forms.CharField(widget=forms.Textarea)

vocab/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Word
from .forms import Addwordform
# Create your views here.

def storewords(request):
    l = []
    tmp = []
    length = len(Word.objects.all())
    length1 = 0
    wrds = []
    alphabets = []
    for i in range(26):
        alphabets.append(chr(i+65))
        select = Word.objects.all().filter(new_word__startswith=chr(i+65))
        length1 = len(select)
    
        if(length1!=0):
            for j in range(length1):
                tmp.append(select[j].new_word)
                tmp.append(select[j].meaning)
                tmp.append(select[j].example)
                #print(tmp)
                l.append(tmp)
                tmp = []
            
            wrds.append([chr(i+65),len(l),l])
           
        l = []
    
    return render(request,'vocab/vocabulary.html',{'words':wrds,'alphabets':alphabets,'range':range(26)})
'''
class Word(models.Model):
    new_word = models.CharField(max_length=100)
    meaning = models.TextField()
    example = models.TextField()

    def __str__(self):
        return self.new_word

            authpassword = form.cleaned_data['authpassword']
            if authpassword == 'None' and authuser == 'None':
                send_mail(subject, message, from_mail, [reciever.email],False)
            else:
                send_mail(subject, message, from_mail, [reciever.email],False, authuser, authpassword,html_message=None)
            redirect('homework:assignhomework')

    return render(request , 'homework/message.html', {'sender':sender,'reciever':reciever,'form':form})

'''
def newword(request):
    form = Addwordform(None)
    if request.method == 'POST':
        form = Addwordform(request.POST)
        if form.is_valid():
            word = form.cleaned_data['word']
            meaning = form.cleaned_data['meaning']
            example = form.cleaned_data['example']
            newword = Word(new_word=word,meaning=meaning,example=example)
            newword.save()
            return redirect('vocab:storewords')
    
    return render(request,'vocab/addword.html',{'form':form})

'''
class Addwordform(forms.Form):
    word = forms.CharField(max_length=100)
    meaning = forms.TextField(widget=forms.Textarea)
    example = forms.TextField(widget=forms.Textarea)
'''


def wordslist(request):
    words= Word.objects.order_by('-id')
    return render(request, 'vocab/vocablist.html',{'words':words})

vocab/templates/vocab/addword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add word</title>
</head>
<body>
    <h1>Add new word here</h1>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit"/>
        </form>
    </div>
</body>
</html>

vocab/templates/vocab/vocablist.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- required meta tags -->
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- bootstrap 4 css -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<title></title>
</head>
<body>

	<!-- Navebar ends -->
  <header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#"><img style="max-width: 40%;" src="{% static 'logo_light2.png' %}"
            alt="logo" /></a></h1></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:home' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'aboutus:aboutus' %}">About Us</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gallery:gallery' %}">Gallery</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:list' %}">Blogs</a>                 
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'video:videopage' %}">Video Of the day</a>                 
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Content
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">JAM</a>
                  <a class="dropdown-item" href="{% url 'homework:assignhomework' %}">Homework</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url  'vocab:storewords' %}">Words</a>
                </div>
            </li>
            
            
          </ul>
        </div>
      </nav>
</header>

	<!-- vocabulary heading -->
<div class="container text-center text-dark">
	<h1>Vocabulary</h1>
	<hr class="w-25 mx-auto pt-5"> 
</div>
<!-- vocabulary heading ends -->



<!-- word meaning table -->
<div class="container">
	<div class="table-responsive-sm">
	<table class="table table-secondary table-hover table-striped">
    <thead>
      <tr>
        <th>Word/Phrase</th>
        <th>Meaning</th>
        <th>Example</th>
      </tr>
    </thead>

    <tbody>
        {% for word in words %}
            <tr id="{{word.id}}">
              <td>{{word.new_word}}</td>
              <td>{{word.meaning}}</td>
              <td>{{word.example}}</td>
            </tr>
        {% endfor %}
    </tbody>
  </table>
  </div>
</div>
<!-- table ends -->
<!-- bootsrap4 scipts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <!-- bootstrap4 scripts ends -->
</body>
</html>

vocab/templates/vocab/vocabulary.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <!-- required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- bootstrap 4 css -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title></title>
</head>

<body>


  <header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#"><img style="max-width: 40%;" src="{% static 'logo_light2.png' %}"
            alt="logo" /></a></h1></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:home' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'aboutus:aboutus' %}">About Us</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gallery:gallery' %}">Gallery</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:list' %}">Blogs</a>                 
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'video:videopage' %}">Video Of the day</a>                 
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Content
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">JAM</a>
                  <a class="dropdown-item" href="{% url 'homework:assignhomework' %}">Homework</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url  'vocab:storewords' %}">Words</a>
                </div>
            </li>
            
            
          </ul>
        </div>
      </nav>
</header>
  <!-- Navebar ends -->

  
  <!-- vocabulary heading -->
  <div class="container text-center text-dark">
    <h1>Vocabulary</h1>
    <hr class="w-25 mx-auto pt-5">
  </div>
  <!-- vocabulary heading ends -->
  <a href="{% url 'vocab:wordlist'%}">VocabListByDate</a>
  <a href="{% url 'vocab:addword' %}">AddNewWord</a>
  <!-- navebar for word letters -->
  <nav class="navbar navbar-expand-sm bg-light justify-content-center mb-5 navbar-light">
    <!-- Links -->
    <ul class="navbar-nav font-weight-bold">
      {%for c in alphabets %}
      <li class="nav-item">
        <a class="nav-link" href="#{{c}}">{{c}}</a>
      </li>
      {% endfor %}
    </ul>
  </nav>
  <!-- navebar for word letters ends -->



  <!-- word meaning table -->
  <div class="container">
    <div class="table-responsive-sm">
      <table class="table table-secondary table-hover table-striped">
        <thead>
          <tr>
            <th>Word/Phrase</th>
            <th>Meaning</th>
            <th>Example</th>
          </tr>
        </thead>
        <tbody>
          <!--loop will start from here-->
          {% for set in words %}
          {% load file %}
          {% for item in set|index:2 %}
          {% if forloop.counter == 1 %}
          <tr id="{{set|index:0}}">
            <td>{{item|index:0}}</td>
            <td>{{item|index:1}}</td>
            <td>{{item|index:2}}</td>
          </tr>
          {% endif %}
          {% if forloop.counter > 1 %}
          <tr>
            <td>{{item|index:0}}</td>
            <td>{{item|index:1}}</td>
            <td>{{item|index:2}}</td>
          </tr>
          {% endif %}
          {% endfor %}
          {% endfor %}
          <!--loop ends here-->
        </tbody>
      </table>
    </div>
  </div>
  <!-- table ends -->


  <!-- bootsrap4 scipts -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <!-- bootstrap4 scripts ends -->
</body>

</html>