Oratory_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib. staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('video/', include('video.urls')),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('aboutus/',include('aboutus.urls')),
    path('homework/',include('homework.urls')),
    path('vocab/',include('vocab.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('gallery/',include('gallery.urls')),
    path('summernote/',include('django_summernote.urls')),
]


urlpatterns+= staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'

urlpatterns=[
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name='login'),
    path("logout/", views.logout_view, name='logout' ),
    
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib. staticfiles.urls import staticfiles_urlpatterns


app_name='articles'
urlpatterns =[
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/',views.article_details, name="detail"),
    
    
]

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns=[
    path('',views.home, name='home'),
]

Oratory_site/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>